#section 1
activity<-read.csv("activity.csv", na.string="NA",header=TRUE, colClasses=c("numeric", "character", "integer"))
activity$date<-as.Date(activity$date, "%Y-%m-%d")

# Calculate total step per date
stepsAllDays<-aggregate(activity$steps, list(activity$date), sum)
colnames(stepsAllDays)<-c("date", "steps")

# create histogram
hist(stepsAllDays$steps,breaks=length(stepsAllDays$date),xlab="total steps taken in a day", main="histogram:total steps each day")

#calculate mean and median
meanSteps<-mean(stepsAllDays$steps, na.rm=TRUE)
medianSteps<-median(stepsAllDays$steps, na.rm=TRUE)


# section 2
stepsAllIntervals<-aggregate(activity$steps, list(activity$interval), na.rm=TRUE,sum)
colnames(stepsAllIntervals)<-c("interval", "steps")
with(stepsAllIntervals, plot(interval, steps, type="l", main="average steps taken during a day"))
stepsAllIntervals[which.max(stepsAllIntervals$steps),c("interval")]


#section 3
#total number of days/internvals with NA
print(paste0("total number of record with missing value:", sum(rowSums(is.na(activity))>0)))

activityFilled=activity
# fill NA values with mean steps of the interval
for(i in 1:nrow(activityFilled)) {
    if (is.na(activityFilled[i, "steps"]) )
    {
       # located an interval with NA steps
       currentInteval=activityFilled[i, "interval"]
       #print(paste0("current internval:",  currentInteval))
       
       # find the mean steps for the interval
       meanSteps<-stepsAllIntervals[stepsAllIntervals$interval==currentInteval,"steps"]
       
       # fill the steps of the current interval with the mean steps of the interval
       activityFilled[i, "steps"]<-meanSteps
       print(paste0("setting internval:",  currentInteval, " ", activity[i, "steps"], "->", activityFilled[i, "steps"]))
    }
}


stepsAllDaysAdjusted<-aggregate(activityFilled$steps, list(activityFilled$date), sum)
colnames(stepsAllDaysAdjusted)<-c("date", "steps")
hist(stepsAllDaysAdjusted$steps,breaks=length(stepsAllDaysAdjusted$date),xlab="total steps taken in a day", main="histogram:adjusted total steps each day")
meanStepsAdjusted<-mean(stepsAllDaysAdjusted$steps, na.rm=TRUE)
medianStepsAdjusted<-median(stepsAllDaysAdjusted$steps, na.rm=TRUE)


#section 4
library(lattice)
convertToWeekDayOrWeekEndDay<-function(x) 
{
     if ((weekdays(x) == "Sunday") |(weekdays(x) == "Saturday"))
     {
        return("weekend")
     } else
     {
        return("weekday")
     }
}

activityFilled$dayOfWeek<-sapply(activityFilled$date, convertToWeekDayOrWeekEndDay)
activityFilled$dayOfWeek<-as.factor(activityFilled$dayOfWeek)
weekdayActivity<-activityFilled[activityFilled$dayOfWeek==weekday,]
weekendActivity<-activityFilled[activityFilled$dayOfWeek=="weekend",]

weekdayStepsAve<-aggregate(weekdayActivity$steps, list(weekdayActivity$interval), mean)
weekendStepsAve<-aggregate(weekendActivity$steps, list(weekendActivity$interval), mean)
colnames(weekdayStepsAve)<-c("interval", "steps")
colnames(weekendStepsAve)<-c("interval", "steps")
weekdayStepsAve$dayOfWeek<-rep("weekday", nrow(weekdayStepsAve))
weekendStepsAve$dayOfWeek<-rep("weekend", nrow(weekendStepsAve))
stepsAveWeekOfDay<-rbind(weekdayStepsAve,weekendStepsAve)
xyplot(steps~interval|dayOfWeek, data=stepsAveWeekOfDay, layout=c(1,2), type="l", ylab="Number of steps", xlab="Interval")

